---
version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  app:
    restart: always
    build: ./api/
    ports:
      - 8888:8888
    command: python main.py
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  worker:
    restart: always
    build: ./worker/
    command: rqworker --url redis://redis:6379/0
