---
version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  app:
    restart: always
    build: 
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - 8888:8888
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python main.py
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  worker:
    restart: always
    build: 
      context: ./
      dockerfile: ./worker/Dockerfile
    command: rqworker --url redis://redis:6379/0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
