---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: jeffs-api
    velocity.tech.v1/dependsOn: mongo-db, jeffs-worker, redis
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      api: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        api: api
    spec:
      containers:
        - name: api
          image: jdvincent/api:latest
          env:
            - name: REDIS_HOST
              # value: redis
              # value: "{velocity.v1:redis.exposures(port=redis).host}"
              value: {{ .Values.redis_host | toJson  }}
            - name: REDIS_PORT
              # value: "6379"
              # value: "{velocity.v1:redis.exposures(port=redis).port}"
              value: {{ .Values.redis_port | toJson  }}
            - name: MONGO_HOST
              # value: mongo
              # value: "{velocity.v1:mongo-db.exposures(port=mongo).host}"
              value: {{ .Values.mongo_host | toJson  }}
            - name: MONGO_PORT
              # value: "27017"
              # value: "{velocity.v1:mongo-db.exposures(port=mongo).port}"
              value: {{ .Values.mongo_port | toJson  }}
          ports:
            - name: api-port
              containerPort: 8888
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: api
  selector:
    app: api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
    - host: api-{velocity.v1.domainSuffix}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8888
